# Generated by Django 4.1.4 on 2022-12-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
