# Generated by Django 4.1.4 on 2022-12-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='annonce_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
