# Generated by Django 4.1.4 on 2022-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_annonce_annonce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
