# Generated by Django 4.1.4 on 2022-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='author',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='title',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
