# Generated by Django 4.1.4 on 2022-12-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_annonce_author_annonce_title_alter_annonce_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avion', models.TextField()),
                ('immat', models.TextField()),
                ('editeur', models.TextField()),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
                ('lien', models.URLField()),
            ],
        ),
    ]
