# Generated by Django 4.1.4 on 2022-12-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_livrees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avion', models.CharField(max_length=100)),
                ('immat', models.CharField(max_length=10)),
                ('editeur', models.CharField(max_length=100)),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
                ('lien', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Livrees',
        ),
    ]
