# Generated by Django 4.1.4 on 2022-12-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_livree_delete_livrees'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('lien', models.URLField()),
                ('year_in_school', models.CharField(choices=[('FT', 'Fonctionnement du club'), ('AT', 'ATO')], default='FT', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='livree',
            name='photo1',
            field=models.ImageField(upload_to='media/dossier_image'),
        ),
        migrations.AlterField(
            model_name='livree',
            name='photo2',
            field=models.ImageField(upload_to='media/dossier_image'),
        ),
    ]
