# Generated by Django 4.1.4 on 2022-12-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_doc_alter_livree_photo1_alter_livree_photo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='doc',
            name='categorie',
            field=models.CharField(choices=[('FT', 'Fonctionnement du club'), ('AT', 'ATO')], default='FT', max_length=2),
        ),
    ]
