# Generated by Django 4.1.4 on 2022-12-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_doc_year_in_school_doc_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livree',
            name='photo1',
            field=models.ImageField(upload_to='dossier_image'),
        ),
        migrations.AlterField(
            model_name='livree',
            name='photo2',
            field=models.ImageField(upload_to='dossier_image'),
        ),
    ]
