# Generated by Django 4.1.4 on 2022-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_livree_photo1_alter_livree_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('InProgress', 'En cours'), ('Soon', 'Programmé'), ('Passed', 'Passed')], default='Soon', max_length=10),
        ),
    ]
