# Generated by Django 4.1.4 on 2022-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='categorie',
            field=models.CharField(choices=[('FT', 'Fonctionnement du club'), ('AT', 'ATO'), ('FR', 'Formations')], default='FT', max_length=2),
        ),
    ]
