# Generated by Django 4.1.4 on 2023-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_formation_alter_doc_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='livree',
            name='categorie',
            field=models.CharField(choices=[('XP', 'X-Plane'), ('MFS', 'Microsoft Flight Sim'), ('PAF', 'Pains accrobatiques')], default='MFS', max_length=3),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(upload_to='dossier_image/'),
        ),
        migrations.AlterField(
            model_name='livree',
            name='photo1',
            field=models.ImageField(upload_to='dossier_image/'),
        ),
        migrations.AlterField(
            model_name='livree',
            name='photo2',
            field=models.ImageField(upload_to='dossier_image/'),
        ),
    ]
