# Generated by Django 4.1.4 on 2023-01-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_livree_categorie_alter_formation_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livree',
            old_name='categorie',
            new_name='simulateur',
        ),
    ]
