# Generated by Django 4.1.4 on 2023-01-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rename_categorie_livree_simulateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lien', models.URLField()),
            ],
        ),
    ]
