# Generated by Django 4.1.4 on 2023-01-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_choice_poll_vote_choice_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
