# Generated by Django 4.1.4 on 2023-01-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_sondage_choixsondage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sondage',
            old_name='question',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='sondage',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
