# Generated by Django 4.1.4 on 2023-01-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_rename_question_sondage_titre_sondage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='type',
            field=models.CharField(choices=[('QCM', 'QCM'), ('CL', 'Champ libre'), ('BI', 'Binaire')], default='QCM', max_length=3),
        ),
    ]
