# Generated by Django 4.1.4 on 2023-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_sondage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livree',
            name='Filtre',
            field=models.CharField(choices=[('AIB', 'AIRBUS'), ('BOE', 'BOEING'), ('LEG', 'LEGER')], default='AIB', max_length=3),
        ),
    ]
