# Generated by Django 4.1.4 on 2023-01-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_livree_filtre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
