# Generated by Django 4.1.4 on 2023-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_remove_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livree',
            name='lien',
        ),
        migrations.AddField(
            model_name='livree',
            name='fichier',
            field=models.FileField(default=0, upload_to='lien_livrees/'),
            preserve_default=False,
        ),
    ]
