# Generated by Django 4.1.4 on 2023-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_remove_livree_lien_livree_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='livree',
            name='ordre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
