# Generated by Django 4.1.4 on 2023-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_livree_options_alter_livree_filtre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALERT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=124)),
                ('lien', models.URLField(blank=True)),
            ],
        ),
    ]
