# Generated by Django 4.1.4 on 2023-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_alert_hyperlink_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmr',
            name='lien',
        ),
        migrations.AddField(
            model_name='vmr',
            name='fichier',
            field=models.FileField(default=0, upload_to='lien_VMR/'),
            preserve_default=False,
        ),
    ]
