# Generated by Django 4.1.4 on 2023-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_rename_filtre_livree_filtre1_livree_filtre2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livree',
            name='Filtre1',
        ),
        migrations.RemoveField(
            model_name='livree',
            name='Filtre2',
        ),
        migrations.RemoveField(
            model_name='livree',
            name='Filtre3',
        ),
        migrations.AddField(
            model_name='livree',
            name='Filtre_constructeur',
            field=models.CharField(blank=True, choices=[('AIRBUS', 'AIRBUS'), ('BOEING', 'BOEING'), ('CESSNA', 'CESSNA')], default='AIRBUS', max_length=6),
        ),
        migrations.AddField(
            model_name='livree',
            name='Filtre_livree',
            field=models.CharField(blank=True, choices=[('CLASSIQUE', 'CLASSIQUE'), ('SPECIALE', 'SPECIALE')], default='CLASSIQUE', max_length=9),
        ),
        migrations.AddField(
            model_name='livree',
            name='Filtre_type',
            field=models.CharField(blank=True, choices=[('LINER', 'LINER'), ('AFFAIRE', 'AFFAIRE'), ('GENERAL', 'GENERAL'), ('HELICO', 'HELICO')], default='LINER', max_length=7),
        ),
    ]
