# Generated by Django 4.1.4 on 2023-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_remove_livree_filtre1_remove_livree_filtre2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
