# Generated by Django 4.1.4 on 2023-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_alter_annonce_author_alter_annonce_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
