# Generated by Django 4.1.4 on 2023-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_qcm_sujet_alter_qcm_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
