# Generated by Django 4.1.4 on 2023-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_eleve_alter_qcm_reponse_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcm',
            name='reponse_correct',
            field=models.IntegerField(choices=[(1, 'Reponse 1'), (2, 'Reponse 2'), (3, 'Reponse 3'), (4, 'Reponse 4')], default=1),
        ),
    ]
