# Generated by Django 4.1.4 on 2023-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_eleve_score_p1'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='autorisation_P1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='score_P1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
