# Generated by Django 4.1.4 on 2023-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_eleve_autorisation_p2_eleve_score_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='score_P1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='score_P2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
